Issue #12: Add Boost include dirs where required
GreatAttractor/imppg pull request #13
Opened 2022-08-26 09:57 UTC by ftclausen

As discussed in issue #12 I am adding the Boost includes in images and backend. Let me know if I missed anything.

2022-08-26 17:16 UTC, GreatAttractor requested changes

2022-08-26 17:16 UTC, GreatAttractor commented on src/backend/CMakeLists.txt
> +target_include_directories(backend PRIVATE ${Boost_INCLUDE_DIRS})
This can also be a single statement:
```CMake
target_include_directories(backend PRIVATE src ${Boost_INCLUDE_DIRS})
```

2022-08-27 01:57 UTC, ftclausen commented on src/backend/CMakeLists.txt
> +target_include_directories(backend PRIVATE ${Boost_INCLUDE_DIRS})
Yup, done.

2022-08-27 09:42 UTC, GreatAttractor approved these changes

2022-08-27 09:43 UTC, merged